name: Core-Terraform-Plan-Apply

on:
  workflow_dispatch:
    inputs:
      component:
        description: Core component
        required: true
        type: choice
        options:
          - network
          - data
          - identity
          - governance

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working_directory: workloads/core/${{ inputs.component }}
      state_key: core/${{ inputs.component }}.tfstate
      component_name: core-${{ inputs.component }}
      tfvars_file: deployment/core/${{ inputs.component }}/${{ inputs.component }}.tfvars
    secrets: inherit

  apply:
    needs: plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: workloads/core/${{ inputs.component }}
      state_key: core/${{ inputs.component }}.tfstate
      component_name: core-${{ inputs.component }}
      environment: core
    secrets: inherit