name: Core-Terraform-Plan-Apply

on:
  workflow_dispatch:
    inputs:
      component:
        description: Core component
        required: true
        type: choice
        options:
          - network
          - data
          - identity
          - governance

jobs:
  plan:
    uses: asliutkarsh/DevSecOps-for-infrastructure-as-code/.github/workflows/terraform-plan.yml@main
    with:
      working_directory: terraform/workloads/core/${{ inputs.component }}
      state_key: core/${{ inputs.component }}.tfstate
      component_name: core-${{ inputs.component }}
      tfvars_file: terraform/deployment/core/${{ inputs.component }}/core.tfvars

  apply:
    needs: plan
    uses: asliutkarsh/DevSecOps-for-infrastructure-as-code/.github/workflows/terraform-apply.yml@main
    with:
      working_directory: terraform/workloads/core/${{ inputs.component }}
      state_key: core/${{ inputs.component }}.tfstate
      component_name: core-${{ inputs.component }}
      environment: core
