name: Spoke-Terraform-Plan-Apply

on:
  workflow_dispatch:
    inputs:
      project:
        description: Spoke project
        required: true
        type: choice
        options:
          - cusbot
          - testproject
      environment:
        description: Spoke environment
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      component:
        description: Spoke component
        required: true
        type: choice
        options:
          - network
          - data
          - identity
          - compute

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working_directory: Workload/Spoke/${{ inputs.project }}/${{ inputs.component }}
      state_key: spoke/${{ inputs.project }}/${{ inputs.environment }}/${{ inputs.component }}.tfstate
      component_name: spoke-${{ inputs.project }}-${{ inputs.component }}
      tfvars_file: Deployment/Spoke/${{ inputs.project }}/${{ inputs.component }}/${{ inputs.environment }}.${{ inputs.component }}.tfvars
      # additional_args: >-
      #   -var="env_name=production"
    secrets: inherit

  apply:
    needs: plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: Workload/Spoke/${{ inputs.project }}/${{ inputs.component }}
      state_key: spoke/${{ inputs.project }}/${{ inputs.environment }}/${{ inputs.component }}.tfstate
      component_name: spoke-${{ inputs.project }}-${{ inputs.component }}
      environment: spoke-${{ inputs.project }}-${{ inputs.environment }}
    secrets: inherit